# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME
#
font_family JetBrainsMonoNL Nerd Font
font_size 12.0

window_decorations none
hide_window_decorations yes
linux_display_server x11
enable_wayland no
enable_audio_bell no

cursor_trail 1
cursor_trail_decay 0.1 0.25
cursor_trail_start_threshold 5
cursor_trail_color #ffffff
